version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    container_name: "ecommerce-db"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
